# Generated by Django 5.2.5 on 2025-08-18 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pointvisit',
            options={'ordering': ['-visit_time']},
        ),
        migrations.AddField(
            model_name='graphpoint',
            name='default_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
