# Generated by Django 5.2.5 on 2025-08-18 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='on_point',
        ),
        migrations.AddField(
            model_name='transaction',
            name='on_visit',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='game.pointvisit'),
            preserve_default=False,
        ),
    ]
