# Generated by Django 5.2.5 on 2025-08-18 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_graphpoint_eval_string'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-visit__visit_time']},
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='on_visit',
            new_name='visit',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_time',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
