# Generated by Django 5.2.5 on 2025-08-18 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_transaction_balance_after'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='visit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='game.pointvisit'),
        ),
    ]
