# Generated by Django 5.2.5 on 2025-08-19 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_alter_transaction_visit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pointvisit',
            name='type',
            field=models.IntegerField(choices=[(1, 'Success'), (2, 'Broke Rule')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pointvisit',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='game.graphpoint'),
        ),
        migrations.AlterField(
            model_name='pointvisit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to=settings.AUTH_USER_MODEL),
        ),
    ]
