# Generated by Django 5.2.5 on 2025-08-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_pointvisit_type_alter_pointvisit_point_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointvisit',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
