# Generated by Django 5.2.5 on 2025-08-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_pointvisit_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphpoint',
            name='x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='graphpoint',
            name='y',
            field=models.FloatField(default=0),
        ),
    ]
