# Generated by Django 5.1.5 on 2025-10-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_rename_eval_string_graphpoint_eval_string_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphpoint',
            name='message_1',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='graphpoint',
            name='message_2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='graphpoint',
            name='message_3',
            field=models.TextField(blank=True, default=''),
        ),
    ]
