# Generated by Django 5.1.5 on 2025-10-05 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_graphpoint_message_1_graphpoint_message_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graphpoint',
            name='default_message',
        ),
    ]
