# Generated by Django 5.1.5 on 2025-10-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_remove_graphpoint_default_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=1000),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='balance_after',
            field=models.DecimalField(decimal_places=2, max_digits=1000),
        ),
    ]
