# Generated by Django 5.2.5 on 2025-10-15 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_reachedzero'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphpoint',
            name='opt_1_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='graphpoint',
            name='opt_2_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='graphpoint',
            name='opt_3_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='graphpoint',
            name='welcome_message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
