# Generated by Django 5.2.5 on 2025-10-16 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_graphpoint_opt_1_message_graphpoint_opt_2_message_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('from_edge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_edges', to='game.graphpoint')),
                ('trigger_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='game.graphpoint')),
                ('users', models.ManyToManyField(blank=True, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
