# Generated by Django 5.2.5 on 2025-10-16 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_achievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='image_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
