# Generated by Django 5.2.5 on 2025-10-16 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0023_achievement_image_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievement',
            old_name='from_edge',
            new_name='from_point',
        ),
        migrations.AlterField(
            model_name='pointvisit',
            name='type',
            field=models.IntegerField(choices=[(1, 'Success'), (2, 'Broke Rule'), (3, 'Achievement')]),
        ),
    ]
